# Generated by Django 5.2.7 on 2026-09-28 21:44

import django.db.models.deletion
import django.utils.timezone
import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Компания')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='На обслуживании')),
            ],
            options={
                'verbose_name': 'Компания на обслуживании',
                'verbose_name_plural': 'Компании на обслуживании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Как называть сервер в отчётах, напр. «SRV-1C»', max_length=120, verbose_name='Сервер')),
                ('token', models.CharField(default=monitoring.models.generate_token, editable=False, max_length=64, unique=True, verbose_name='Токен')),
                ('hostname', models.CharField(blank=True, help_text='Заполняется скриптом автоматически', max_length=120, verbose_name='Имя компьютера')),
                ('os_info', models.CharField(blank=True, max_length=200, verbose_name='ОС')),
                ('agent_version', models.CharField(blank=True, max_length=40, verbose_name='Версия скриптов')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний отчёт')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP последнего отчёта')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отслеживать')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='monitoring.monitoredcompany', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сервер клиента',
                'verbose_name_plural': 'Сервера клиентов',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникально в пределах сервера, задаётся скриптом', max_length=160, verbose_name='Задание')),
                ('kind', models.CharField(choices=[('backup', 'Резервная копия'), ('health', 'Состояние сервера'), ('check', 'Проверка')], default='backup', max_length=10, verbose_name='Тип')),
                ('engine', models.CharField(blank=True, choices=[('postgresql', 'PostgreSQL'), ('mssql', 'MS SQL'), ('1c', '1С (выгрузка .dt)'), ('files', 'Файлы'), ('other', 'Другое')], max_length=12, verbose_name='СУБД / источник')),
                ('database', models.CharField(blank=True, max_length=160, verbose_name='База')),
                ('expected_every_hours', models.PositiveIntegerField(default=24, help_text='Если отчёта нет дольше (плюс запас) — задание считается пропущенным', verbose_name='Отчёт ожидается каждые, ч')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отслеживать')),
                ('last_status', models.CharField(blank=True, choices=[('ok', 'Норма'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], max_length=10, verbose_name='Последний статус')),
                ('last_report_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний отчёт')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='monitoring.monitoredhost', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания (бэкапы и проверки)',
                'ordering': ['host__company__name', 'host__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Получен')),
                ('status', models.CharField(choices=[('ok', 'Норма'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], max_length=10, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Размер, байт')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Файл / путь')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='monitoring.job', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='monitoredhost',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='monitoring_host_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('host', 'name'), name='monitoring_job_unique_name'),
        ),
    ]
