"""
Django settings for Shop project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0', cast=Csv())

# Доверенные источники для CSRF (нужно при доступе через HTTPS-туннель, напр. Cloudflare).
# Формат значений: со схемой, можно с поддоменным шаблоном — https://*.trycloudflare.com
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# --- HTTPS за обратным прокси / туннелем ---
# TLS терминируется на прокси (cloudflared / nginx), поэтому доверяем заголовку
# X-Forwarded-Proto. Без этого Django считает запрос http и строит http://-canonical,
# http-sitemap и отдаёт cookie без флага Secure (см. SEO/безопасность).
# ВАЖНО: приложение должно быть доступно ТОЛЬКО через прокси (порт биндить на 127.0.0.1),
# иначе клиент сможет подделать этот заголовок.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Редирект http→https делает прокси/туннель; при прямом заходе подстрахует Django.
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    # HSTS включать осознанно, только когда весь трафик уже на https (иначе можно
    # заблокировать себе доступ). Значение в секундах, 0 — выключено.
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # тема админки — должна идти ПЕРЕД django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'main',
    'index',
    'content',
    'accounts',
    'mptt',
    'easy_pdf',
    'django_ckeditor_5',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.cart_quantity',
                'index.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'Shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# По умолчанию — sqlite (локальная разработка). В Docker/прод задаётся через переменные
# окружения (POSTGRES_*) и используется PostgreSQL.
if config('POSTGRES_DB', default=''):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('POSTGRES_DB'),
            'USER': config('POSTGRES_USER', default='postgres'),
            'PASSWORD': config('POSTGRES_PASSWORD', default=''),
            'HOST': config('POSTGRES_HOST', default='db'),
            'PORT': config('POSTGRES_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True


PRODUCTS_PER_PAGE = 12

# --- CKEditor 5 (rich-text для статей и кейсов) ---
customColorPalette = []
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'link', 'underline',
            'bulletedList', 'numberedList', 'blockQuote', '|',
            'imageUpload', 'insertTable', '|',
            'undo', 'redo',
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignRight', 'imageStyle:full',
            ],
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells'],
        },
    },
}
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'jpg', 'png', 'gif', 'webp']
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Аутентификация (вход по email или телефону) ---
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/profile/'
LOGOUT_REDIRECT_URL = '/'

TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
# Список ID администраторов (через запятую). Поддерживаем и старый TELEGRAM_ADMIN_ID.
TELEGRAM_CHAT_IDS = [
    int(x) for x in config('TELEGRAM_ADMIN_IDS', default=config('TELEGRAM_ADMIN_ID', default=''), cast=Csv())
    if str(x).strip() and str(x).strip() != '0'
]
# Обратная совместимость: первый ID как одиночный chat_id
TELEGRAM_CHAT_ID = TELEGRAM_CHAT_IDS[0] if TELEGRAM_CHAT_IDS else 0

# --- Email ---
# По умолчанию письма печатаются в консоль (работает без SMTP).
# Для боевой отправки задайте в .env: EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend + хост/логин/пароль.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Лаборатория ВТ <noreply@laboratoriya-vt.ru>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# --- Celery ---
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Если брокер недоступен (например, локально без Redis) — задачи выполнятся синхронно.
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)

# --- Оформление админ-панели (django-jazzmin) ---
# Тематическая группировка моделей задаётся в Shop/admin_groups.py (кастомный get_app_list).
# Иконки ниже привязаны к синтетическим app_label групп: "grp_<группа>.<модель>".
JAZZMIN_SETTINGS = {
    'site_title': 'Лаборатория ВТ',
    'site_header': 'Лаборатория ВТ',
    'site_brand': 'Лаборатория ВТ',
    'welcome_sign': 'Панель управления сайтом «Лаборатория ВТ»',
    'copyright': 'Лаборатория ВТ',
    'search_model': ['main.Product', 'index.Lead'],
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'language_chooser': False,
    'related_modal_active': True,
    'topmenu_links': [
        {'name': 'Открыть сайт', 'url': '/', 'new_window': True},
        {'model': 'main.order'},
        {'model': 'index.lead'},
    ],
    'default_icon_parents': 'fas fa-folder',
    'default_icon_children': 'fas fa-circle',
    'icons': {
        # Контент
        'grp_content.service': 'fas fa-screwdriver-wrench',
        'grp_content.project': 'fas fa-diagram-project',
        'grp_content.article': 'fas fa-newspaper',
        'grp_content.faqitem': 'fas fa-circle-question',
        'grp_content.mediaitem': 'fas fa-photo-film',
        'grp_content.landing': 'fas fa-bullhorn',
        # Оформление сайта
        'grp_design.servicecard': 'fas fa-grip',
        'grp_design.advantage': 'fas fa-circle-check',
        'grp_design.companystat': 'fas fa-chart-simple',
        'grp_design.teamcontact': 'fas fa-address-card',
        'grp_design.partner': 'fas fa-handshake',
        # Настройки
        'grp_settings.sitesettings': 'fas fa-gear',
        # Магазин
        'grp_shop.category': 'fas fa-folder-tree',
        'grp_shop.product': 'fas fa-box',
        'grp_shop.productvariant': 'fas fa-boxes-stacked',
        'grp_shop.productproperty': 'fas fa-list',
        'grp_shop.productimage': 'fas fa-image',
        'grp_shop.review': 'fas fa-star',
        # Заявки и заказы
        'grp_orders.lead': 'fas fa-inbox',
        'grp_orders.order': 'fas fa-receipt',
        'grp_orders.orderitem': 'fas fa-list-check',
        # Служебное
        'grp_system.profile': 'fas fa-id-badge',
        'grp_system.user': 'fas fa-user',
        'grp_system.group': 'fas fa-users',
        'grp_system.session': 'fas fa-clock-rotate-left',
        'grp_system.logentry': 'fas fa-clipboard-list',
    },
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'dark_mode_theme': 'darkly',
    'navbar': 'navbar-white navbar-light',
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_flat_style': False,
    'sidebar_fixed': True,
    'navbar_fixed': True,
    'footer_fixed': False,
    'actions_sticky_top': True,
    'accent': 'accent-primary',
    'brand_colour': 'navbar-primary',
    'body_small_text': False,
    'sidebar_nav_small_text': False,
}