# Generated by Django 5.2.7 on 2026-04-10 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_payment_method_alter_order_status_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Отметьте, если клиент погасил задолженность по данному заказу', verbose_name='Оплачен (для постоплаты)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дебиторская задолженность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reserved_postpay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарезервировано по постоплате'),
        ),
    ]
